### ISSUE TITLE
Which field to use in models.py ?

### ISSUE THREAD

**Issue by calofmijuck** [thunderlink/ThunderFish#12]
I think we need to discuss what kind of fields to use for the commented fields in the code below.

1. Some fields may not be necessary, we can use foreign key instead. (comment field in User)
2. What to do with tag (Meeting), region (User/Meeting) field?
3. meeting_hosted, meeting_participated: Should these be managed by foreign key, or ArrayField?

https://github.com/thunderlink/ThunderFish/blob/58b91ba8157d03083be95a7c5bb4466857f015a0/backend/server/models.py#L7-L17

https://github.com/thunderlink/ThunderFish/blob/58b91ba8157d03083be95a7c5bb4466857f015a0/backend/server/models.py#L25-L38

**Comment by KRKimDongWoo** [comment]
Check for the M:N relations

**Comment by KRKimDongWoo** [comment]
Resolved. close
