### ISSUE TITLE
Suggesting Badge system

### ISSUE THREAD

**Issue by KRKimDongWoo** [thunderlink/ThunderFish#17]
I'm currently making a user detail page (Also will be similar to my page), and I'm referencing the user page of the steampowered.com.
 Here's my idea: how about also using badge system, just like in github or steam? I'm curently thinking of these -
1. newcommer (signed up 1 week ago)
2. hoster (hosted 10+ meetings)
3. joiner ( joined 10+ meetings)
4. clean user (never get reported for 1 month)
...
also with number of reports user got

**Comment by givenone** [comment]
Good idea. But i think its somewhat deluxe(?) part.

Maybe we can add this feature later on after completing all the other features.

**Comment by corvuspink** [comment]
I think it's not difficult to implement - just add some model, without changing the existing structure
So we can add this feature easily after we make basic features.

**Comment by calofmijuck** [comment]
I like the idea. We should consider implementing it. But first things first, we should set up the basic features for now.

**Comment by KRKimDongWoo** [comment]
Will not be implemented in current Project. Closed
