### ISSUE TITLE
Things we need to discuss

### ISSUE THREAD

**Issue by givenone** [thunderlink/ThunderFish#22]
The list below is the things we need to discuss on tomorrow meetings. Please add any other ideas.

1. Something more algorithmic
I think we should think more about some features running on backend. Not only searching algorithms, I thought there are more to discuss. The examples are listed below. Let's discuss it tomorrow.

Even if these are not basic features, but I think we need to keep in mind about these.

-  Notification system : how to notify? (what @corvuspink mentioned)
-  Charging system : how to charge and cost field
-  Recommendation system : What meetings to be shown, if not searched? (just on main page)
- etc..

2. Testing
As you know, we need to test our implementations. So we need to discuss which testing tools to use and how to use it.

3. Authentication System
The service need to have authentication system when signing up. Maybe we can check email,  phone number, real-name by using Api. Also, we may need to implement checking already existing users or something like this in the backend.
I've heard that django have some builtin apis for authentication. Lets discuss about it.

Let's roll! Sorry for being lazy...

**Comment by givenone** [comment]
+ I will complete progress report before 10. Please check it.

**Comment by corvuspink** [comment]
Small topic for 1 : How to handle region system

**Comment by givenone** [comment]
+ notification handling ::

**Comment by KRKimDongWoo** [comment]
Notification System and Authentication System implemented, Testing is still going on.
