### ISSUE TITLE
Things we should do until next week

### ISSUE THREAD

**Issue by givenone** [thunderlink/ThunderFish#29]
- Make runable views.py and serializers.py for Apis(GET, POST, PUT, DELETE) according to design document.
 -> @calofmijuck and @corvuspink will contribute for it. If they are internally and emotionally well-being.

- Make python test : test.py for testing backend Apis
-> I will try hard. (maybe)

- Make actions and reducers for frontend and connect it with components
 -> I will maybe make demo version of actions. @KRKimDongWoo will finally confirm and contribute for it after ha-si-sul.

- Implement Jest for react coverage and module testing
 -> I am studying on it. Lets discuss it more next week.

Fun Weekend.

**Comment by KRKimDongWoo** [comment]
milestone finished, implementing tests for now.
