### ISSUE TITLE
[Howto] Add new pull requests

### ISSUE THREAD

**Issue by KRKimDongWoo** [thunderlink/ThunderFish#3]
### 1. clone
 Clone forked repository to local storage.
`$ git clone https://github.com/thunderlink/ThunderFish.git `

### 2. create branch
Make a branch
`$ git checkout -b BRANCH_NAME`

### 3. add, commit, push
Modify the code and run following three commands
`$ git add .`
`$ git commit -m "what I did"`
`$ git push origin BRANCH_NAME`

### 4. Make pull request
Make a pull request in main repository by press 'new pull request' button.

### 5. Code review & Merge pull request
Check the code and merge.

**Comment by calofmijuck** [comment]
Thanks for the reference.
